Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -45,9 +45,18 @@ jobs:
       
     - name: Test
       run: dotnet test --logger "trx;logfilename=TestResults.trx" --results-directory ./TestsReport --no-build --collect:"XPlat Code Coverage"
+      
     - name: Create coverage report
       run: reportgenerator -reports:TestsReport/**/coverage.cobertura.xml -targetdir:TestsReport -reporttypes:Cobertura
       
+    - name: Create tests report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Tests Report     # Name of the check run which will be created
+        path: TestsReport/*.trx    # Path to test results
+        reporter: dotnet-trx     # Format of test results
+
     - name: Post result
       uses: bibipkins/dotnet-test-reporter@v1.0.0
       if: success() || failure()    # run this step even if previous step failed
@@ -58,20 +67,3 @@ jobs:
         comment-title: 'Unit Test Results'
         post-new-comment: true
         coverage-type: cobertura
-      
-    - name: Create tests report
-      uses: dorny/test-reporter@v1
-      if: success() || failure()    # run this step even if previous step failed
-      with:
-        name: Tests Report     # Name of the check run which will be created
-        path: TestsReport/*.trx    # Path to test results
-        reporter: dotnet-trx     # Format of test results
-        
-    - name: Code Coverage Report
-      uses: irongut/CodeCoverageSummary@v1.3.0
-      with:
-        filename: TestsReport/Cobertura.xml
-        format: markdown
-        hide_branch_rate: false
-        hide_complexity: true
-        output: both
